package com.yukisora.yukiaccount.data.model

import com.yukisora.yukiaccount.domain.model.Account
import com.yukisora.yukiaccount.domain.model.InvestmentAsset
import com.yukisora.yukiaccount.domain.model.Money
import com.yukisora.yukiaccount.domain.model.RecurringRule
import com.yukisora.yukiaccount.domain.model.SkippedOccurrence
import com.yukisora.yukiaccount.domain.model.Transaction

fun AccountEntity.toDomain(): Account =
    Account(
        id = id,
        name = name,
        type = type,
        balance = Money.cents(balanceCents),
        creditLimit = creditLimitCents?.let(Money::cents),
        billingDay = billingDay,
        repaymentDay = repaymentDay,
        isArchived = isArchived,
    )

fun Account.toEntity(now: Long): AccountEntity =
    AccountEntity(
        id = id,
        name = name,
        type = type,
        balanceCents = balance.cents,
        creditLimitCents = creditLimit?.cents,
        billingDay = billingDay,
        repaymentDay = repaymentDay,
        isArchived = isArchived,
        createdAt = now,
        updatedAt = now,
    )

fun InvestmentAssetEntity.toDomain(): InvestmentAsset =
    InvestmentAsset(
        id = id,
        name = name,
        type = type,
        principal = Money.cents(principalCents),
        currentValue = Money.cents(currentValueCents),
        lastValuationDate = lastValuationDate,
        isArchived = isArchived,
    )

fun InvestmentAsset.toEntity(now: Long): InvestmentAssetEntity =
    InvestmentAssetEntity(
        id = id,
        name = name,
        type = type,
        principalCents = principal.cents,
        currentValueCents = currentValue.cents,
        lastValuationDate = lastValuationDate,
        isArchived = isArchived,
        createdAt = now,
        updatedAt = now,
    )

fun TransactionEntity.toDomain(): Transaction =
    Transaction(
        id = id,
        type = type,
        amount = Money.cents(amountCents),
        accountId = accountId,
        targetAccountId = targetAccountId,
        categoryId = categoryId,
        investmentAssetId = investmentAssetId,
        date = date,
        note = note,
        autoGenerated = autoGenerated,
        recurringRuleId = recurringRuleId,
        occurrenceDate = occurrenceDate,
    )

fun Transaction.toEntity(now: Long): TransactionEntity =
    TransactionEntity(
        id = id,
        type = type,
        amountCents = amount.cents,
        accountId = accountId,
        targetAccountId = targetAccountId,
        categoryId = categoryId,
        investmentAssetId = investmentAssetId,
        date = date,
        note = note,
        autoGenerated = autoGenerated,
        recurringRuleId = recurringRuleId,
        occurrenceDate = occurrenceDate,
        createdAt = now,
        updatedAt = now,
    )

fun RecurringRuleEntity.toDomain(): RecurringRule =
    RecurringRule(
        id = id,
        name = name,
        transactionType = transactionType,
        amount = Money.cents(amountCents),
        accountId = accountId,
        targetAccountId = targetAccountId,
        categoryId = categoryId,
        investmentAssetId = investmentAssetId,
        frequency = frequency,
        startDate = startDate,
        endDate = endDate,
        nextOccurrenceDate = nextOccurrenceDate,
        enabled = enabled,
    )

fun RecurringRule.toEntity(now: Long): RecurringRuleEntity =
    RecurringRuleEntity(
        id = id,
        name = name,
        transactionType = transactionType,
        amountCents = amount.cents,
        accountId = accountId,
        targetAccountId = targetAccountId,
        categoryId = categoryId,
        investmentAssetId = investmentAssetId,
        frequency = frequency,
        startDate = startDate,
        endDate = endDate,
        nextOccurrenceDate = nextOccurrenceDate,
        enabled = enabled,
        createdAt = now,
        updatedAt = now,
    )

fun SkippedOccurrenceEntity.toDomain(): SkippedOccurrence =
    SkippedOccurrence(
        recurringRuleId = recurringRuleId,
        occurrenceDate = occurrenceDate,
        reason = reason,
    )

fun SkippedOccurrence.toEntity(id: String, now: Long): SkippedOccurrenceEntity =
    SkippedOccurrenceEntity(
        id = id,
        recurringRuleId = recurringRuleId,
        occurrenceDate = occurrenceDate,
        reason = reason,
        createdAt = now,
    )
