package com.yukisora.yukiaccount.data.model

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import com.yukisora.yukiaccount.domain.model.AccountType
import com.yukisora.yukiaccount.domain.model.InvestmentType
import com.yukisora.yukiaccount.domain.model.RecurringFrequency
import com.yukisora.yukiaccount.domain.model.TransactionType
import java.time.LocalDate

@Entity(tableName = "accounts")
data class AccountEntity(
    @PrimaryKey val id: String,
    val name: String,
    val type: AccountType,
    val balanceCents: Long,
    val creditLimitCents: Long?,
    val billingDay: Int?,
    val repaymentDay: Int?,
    val isArchived: Boolean,
    val createdAt: Long,
    val updatedAt: Long,
)

@Entity(tableName = "categories")
data class CategoryEntity(
    @PrimaryKey val id: String,
    val name: String,
    val type: String,
    val isFixedExpense: Boolean,
    val sortOrder: Int,
    val isArchived: Boolean,
)

@Entity(
    tableName = "transactions",
    indices = [
        Index(value = ["date"]),
        Index(value = ["accountId"]),
        Index(value = ["recurringRuleId", "occurrenceDate"], unique = true),
    ],
)
data class TransactionEntity(
    @PrimaryKey val id: String,
    val type: TransactionType,
    val amountCents: Long,
    val accountId: String,
    val targetAccountId: String?,
    val categoryId: String?,
    val investmentAssetId: String?,
    val date: LocalDate,
    val note: String,
    val autoGenerated: Boolean,
    val recurringRuleId: String?,
    val occurrenceDate: LocalDate?,
    val createdAt: Long,
    val updatedAt: Long,
)

@Entity(tableName = "recurring_rules")
data class RecurringRuleEntity(
    @PrimaryKey val id: String,
    val name: String,
    val transactionType: TransactionType,
    val amountCents: Long,
    val accountId: String,
    val targetAccountId: String?,
    val categoryId: String?,
    val investmentAssetId: String?,
    val frequency: RecurringFrequency,
    val startDate: LocalDate,
    val endDate: LocalDate?,
    val nextOccurrenceDate: LocalDate,
    val enabled: Boolean,
    val createdAt: Long,
    val updatedAt: Long,
)

@Entity(tableName = "investment_assets")
data class InvestmentAssetEntity(
    @PrimaryKey val id: String,
    val name: String,
    val type: InvestmentType,
    val principalCents: Long,
    val currentValueCents: Long,
    val lastValuationDate: LocalDate?,
    val isArchived: Boolean,
    val createdAt: Long,
    val updatedAt: Long,
)

@Entity(
    tableName = "valuation_snapshots",
    indices = [Index(value = ["investmentAssetId", "date"])],
)
data class ValuationSnapshotEntity(
    @PrimaryKey val id: String,
    val investmentAssetId: String,
    val date: LocalDate,
    val valueCents: Long,
    val note: String,
    val createdAt: Long,
)

@Entity(
    tableName = "skipped_occurrences",
    indices = [Index(value = ["recurringRuleId", "occurrenceDate"], unique = true)],
)
data class SkippedOccurrenceEntity(
    @PrimaryKey val id: String,
    val recurringRuleId: String,
    val occurrenceDate: LocalDate,
    val reason: String,
    val createdAt: Long,
)
