package com.yukisora.yukiaccount.domain.service

import com.yukisora.yukiaccount.domain.model.RecurringFrequency
import com.yukisora.yukiaccount.domain.model.RecurringRule
import com.yukisora.yukiaccount.domain.model.SkippedOccurrence
import com.yukisora.yukiaccount.domain.model.Transaction
import java.time.LocalDate

object RecurringGenerator {
    fun generate(
        rules: List<RecurringRule>,
        existingTransactions: List<Transaction>,
        skippedOccurrences: List<SkippedOccurrence>,
        today: LocalDate,
    ): RecurringGenerationResult {
        val generated = mutableListOf<Transaction>()
        val updatedRules = rules.map { rule ->
            if (!rule.enabled) {
                rule
            } else {
                var occurrence = rule.nextOccurrenceDate
                var nextOccurrence = occurrence

                while (!occurrence.isAfter(today) && !isAfterEndDate(occurrence, rule)) {
                    if (!hasExisting(existingTransactions, rule.id, occurrence) &&
                        !isSkipped(skippedOccurrences, rule.id, occurrence)
                    ) {
                        generated += rule.toTransaction(occurrence)
                    }
                    occurrence = occurrence.next(rule.frequency)
                    nextOccurrence = occurrence
                }

                rule.copy(nextOccurrenceDate = nextOccurrence)
            }
        }

        return RecurringGenerationResult(
            transactions = generated,
            updatedRules = updatedRules,
        )
    }

    private fun hasExisting(
        transactions: List<Transaction>,
        ruleId: String,
        occurrenceDate: LocalDate,
    ): Boolean =
        transactions.any {
            it.autoGenerated &&
                it.recurringRuleId == ruleId &&
                it.occurrenceDate == occurrenceDate
        }

    private fun isSkipped(
        skippedOccurrences: List<SkippedOccurrence>,
        ruleId: String,
        occurrenceDate: LocalDate,
    ): Boolean =
        skippedOccurrences.any {
            it.recurringRuleId == ruleId && it.occurrenceDate == occurrenceDate
        }

    private fun isAfterEndDate(date: LocalDate, rule: RecurringRule): Boolean =
        rule.endDate?.let { date.isAfter(it) } ?: false

    private fun RecurringRule.toTransaction(occurrenceDate: LocalDate): Transaction =
        Transaction(
            id = "${id}_${occurrenceDate}",
            type = transactionType,
            amount = amount,
            accountId = accountId,
            targetAccountId = targetAccountId,
            categoryId = categoryId,
            investmentAssetId = investmentAssetId,
            date = occurrenceDate,
            autoGenerated = true,
            recurringRuleId = id,
            occurrenceDate = occurrenceDate,
        )

    private fun LocalDate.next(frequency: RecurringFrequency): LocalDate =
        when (frequency) {
            RecurringFrequency.DAILY -> plusDays(1)
            RecurringFrequency.WEEKLY -> plusWeeks(1)
            RecurringFrequency.MONTHLY -> plusMonths(1)
        }
}

data class RecurringGenerationResult(
    val transactions: List<Transaction>,
    val updatedRules: List<RecurringRule>,
)
