package com.yukisora.yukiaccount.domain.service

import com.yukisora.yukiaccount.domain.model.Money
import com.yukisora.yukiaccount.domain.model.RecurringFrequency
import com.yukisora.yukiaccount.domain.model.RecurringRule
import com.yukisora.yukiaccount.domain.model.SkippedOccurrence
import com.yukisora.yukiaccount.domain.model.Transaction
import com.yukisora.yukiaccount.domain.model.TransactionType
import org.junit.Test
import java.time.LocalDate
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class RecurringGeneratorTest {
    @Test
    fun monthlyRuleGeneratesMissingOccurrencesThroughToday() {
        val rule = rule(
            frequency = RecurringFrequency.MONTHLY,
            nextOccurrenceDate = LocalDate.of(2026, 5, 10),
        )

        val result = RecurringGenerator.generate(
            rules = listOf(rule),
            existingTransactions = emptyList(),
            skippedOccurrences = emptyList(),
            today = LocalDate.of(2026, 7, 10),
        )

        assertEquals(
            listOf(LocalDate.of(2026, 5, 10), LocalDate.of(2026, 6, 10), LocalDate.of(2026, 7, 10)),
            result.transactions.map { it.occurrenceDate },
        )
        assertEquals(LocalDate.of(2026, 8, 10), result.updatedRules.single().nextOccurrenceDate)
    }

    @Test
    fun dailyInvestmentRuleGeneratesAutoInvestmentBuyTransactionsThroughToday() {
        val rule = rule(
            id = "daily-invest",
            transactionType = TransactionType.INVESTMENT_BUY,
            frequency = RecurringFrequency.DAILY,
            nextOccurrenceDate = LocalDate.of(2026, 7, 5),
            investmentAssetId = "fund",
        )

        val result = RecurringGenerator.generate(
            rules = listOf(rule),
            existingTransactions = emptyList(),
            skippedOccurrences = emptyList(),
            today = LocalDate.of(2026, 7, 7),
        )

        assertEquals(3, result.transactions.size)
        assertTrue(result.transactions.all { it.type == TransactionType.INVESTMENT_BUY })
        assertTrue(result.transactions.all { it.autoGenerated })
        assertTrue(result.transactions.all { it.recurringRuleId == "daily-invest" })
        assertTrue(result.transactions.all { it.investmentAssetId == "fund" })
        assertEquals(LocalDate.of(2026, 7, 8), result.updatedRules.single().nextOccurrenceDate)
    }

    @Test
    fun existingRuleIdAndOccurrenceDatePreventsDuplicateGeneration() {
        val rule = rule(nextOccurrenceDate = LocalDate.of(2026, 7, 1))
        val existing = generatedTransaction(ruleId = rule.id, occurrenceDate = LocalDate.of(2026, 7, 1))

        val result = RecurringGenerator.generate(
            rules = listOf(rule),
            existingTransactions = listOf(existing),
            skippedOccurrences = emptyList(),
            today = LocalDate.of(2026, 7, 1),
        )

        assertEquals(emptyList(), result.transactions)
        assertEquals(LocalDate.of(2026, 8, 1), result.updatedRules.single().nextOccurrenceDate)
    }

    @Test
    fun skippedOccurrenceIsNotGenerated() {
        val rule = rule(nextOccurrenceDate = LocalDate.of(2026, 7, 1))
        val skipped = SkippedOccurrence(
            recurringRuleId = rule.id,
            occurrenceDate = LocalDate.of(2026, 7, 1),
        )

        val result = RecurringGenerator.generate(
            rules = listOf(rule),
            existingTransactions = emptyList(),
            skippedOccurrences = listOf(skipped),
            today = LocalDate.of(2026, 7, 1),
        )

        assertEquals(emptyList(), result.transactions)
        assertEquals(LocalDate.of(2026, 8, 1), result.updatedRules.single().nextOccurrenceDate)
    }

    @Test
    fun disabledRuleDoesNotGenerateTransactions() {
        val rule = rule(enabled = false, nextOccurrenceDate = LocalDate.of(2026, 7, 1))

        val result = RecurringGenerator.generate(
            rules = listOf(rule),
            existingTransactions = emptyList(),
            skippedOccurrences = emptyList(),
            today = LocalDate.of(2026, 7, 7),
        )

        assertEquals(emptyList(), result.transactions)
        assertEquals(rule, result.updatedRules.single())
    }

    private fun rule(
        id: String = "rule",
        transactionType: TransactionType = TransactionType.EXPENSE,
        frequency: RecurringFrequency = RecurringFrequency.MONTHLY,
        nextOccurrenceDate: LocalDate = LocalDate.of(2026, 7, 1),
        investmentAssetId: String? = null,
        enabled: Boolean = true,
    ) = RecurringRule(
        id = id,
        name = id,
        transactionType = transactionType,
        amount = Money.cents(1_000),
        accountId = "bank",
        targetAccountId = null,
        categoryId = "fixed",
        investmentAssetId = investmentAssetId,
        frequency = frequency,
        startDate = LocalDate.of(2026, 1, 1),
        endDate = null,
        nextOccurrenceDate = nextOccurrenceDate,
        enabled = enabled,
    )

    private fun generatedTransaction(ruleId: String, occurrenceDate: LocalDate) = Transaction(
        id = "existing",
        type = TransactionType.EXPENSE,
        amount = Money.cents(1_000),
        accountId = "bank",
        targetAccountId = null,
        categoryId = "fixed",
        investmentAssetId = null,
        date = occurrenceDate,
        autoGenerated = true,
        recurringRuleId = ruleId,
        occurrenceDate = occurrenceDate,
    )
}
