package com.yukisora.yukiaccount.domain.service

import com.yukisora.yukiaccount.domain.model.Money
import com.yukisora.yukiaccount.domain.model.TransactionType
import java.time.LocalDate
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse

class TransactionFactoryTest {
    @Test
    fun creditCardRepaymentCreatesTransferLikeRepaymentTransaction() {
        val transaction = TransactionFactory.creditCardRepayment(
            id = "repayment",
            amount = Money.cents(12_000),
            sourceAccountId = "bank",
            creditCardAccountId = "credit-card",
            date = LocalDate.of(2026, 7, 8),
            note = "本月还款",
        )

        assertEquals(TransactionType.CREDIT_CARD_REPAYMENT, transaction.type)
        assertEquals(Money.cents(12_000), transaction.amount)
        assertEquals("bank", transaction.accountId)
        assertEquals("credit-card", transaction.targetAccountId)
        assertEquals(LocalDate.of(2026, 7, 8), transaction.date)
        assertEquals("本月还款", transaction.note)
        assertFalse(transaction.autoGenerated)
    }
}
