package com.yukisora.yukiaccount.domain.service

import com.yukisora.yukiaccount.domain.model.Money
import com.yukisora.yukiaccount.domain.model.TransactionType
import java.time.LocalDate
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse

class TransactionFactoryTest {
    @Test
    fun expenseCreatesTransactionWithCategory() {
        val transaction = TransactionFactory.expense(
            id = "expense",
            amount = Money.cents(4_200),
            accountId = "bank",
            categoryId = "food",
            date = LocalDate.of(2026, 7, 10),
            note = "lunch",
        )

        assertEquals(TransactionType.EXPENSE, transaction.type)
        assertEquals(Money.cents(4_200), transaction.amount)
        assertEquals("bank", transaction.accountId)
        assertEquals("food", transaction.categoryId)
        assertEquals(LocalDate.of(2026, 7, 10), transaction.date)
        assertEquals("lunch", transaction.note)
        assertFalse(transaction.autoGenerated)
    }

    @Test
    fun incomeCreatesTransactionWithCategory() {
        val transaction = TransactionFactory.income(
            id = "income",
            amount = Money.cents(20_000),
            accountId = "bank",
            categoryId = "salary",
            date = LocalDate.of(2026, 7, 10),
            note = "payday",
        )

        assertEquals(TransactionType.INCOME, transaction.type)
        assertEquals(Money.cents(20_000), transaction.amount)
        assertEquals("bank", transaction.accountId)
        assertEquals("salary", transaction.categoryId)
        assertEquals(LocalDate.of(2026, 7, 10), transaction.date)
        assertEquals("payday", transaction.note)
        assertFalse(transaction.autoGenerated)
    }

    @Test
    fun refundCreatesRefundTransactionForOriginalAccount() {
        val transaction = TransactionFactory.refund(
            id = "refund",
            amount = Money.cents(3_000),
            accountId = "bank",
            categoryId = "food",
            date = LocalDate.of(2026, 7, 9),
            note = "退货退款",
        )

        assertEquals(TransactionType.REFUND, transaction.type)
        assertEquals(Money.cents(3_000), transaction.amount)
        assertEquals("bank", transaction.accountId)
        assertEquals("food", transaction.categoryId)
        assertEquals(LocalDate.of(2026, 7, 9), transaction.date)
        assertEquals("退货退款", transaction.note)
        assertFalse(transaction.autoGenerated)
    }

    @Test
    fun transferCreatesTransactionWithSourceAndTargetAccounts() {
        val transaction = TransactionFactory.transfer(
            id = "transfer",
            amount = Money.cents(8_000),
            sourceAccountId = "bank",
            targetAccountId = "cash",
            date = LocalDate.of(2026, 7, 9),
            note = "取现",
        )

        assertEquals(TransactionType.TRANSFER, transaction.type)
        assertEquals(Money.cents(8_000), transaction.amount)
        assertEquals("bank", transaction.accountId)
        assertEquals("cash", transaction.targetAccountId)
        assertEquals(LocalDate.of(2026, 7, 9), transaction.date)
        assertEquals("取现", transaction.note)
        assertFalse(transaction.autoGenerated)
    }

    @Test
    fun creditCardRepaymentCreatesTransferLikeRepaymentTransaction() {
        val transaction = TransactionFactory.creditCardRepayment(
            id = "repayment",
            amount = Money.cents(12_000),
            sourceAccountId = "bank",
            creditCardAccountId = "credit-card",
            date = LocalDate.of(2026, 7, 8),
            note = "本月还款",
        )

        assertEquals(TransactionType.CREDIT_CARD_REPAYMENT, transaction.type)
        assertEquals(Money.cents(12_000), transaction.amount)
        assertEquals("bank", transaction.accountId)
        assertEquals("credit-card", transaction.targetAccountId)
        assertEquals(LocalDate.of(2026, 7, 8), transaction.date)
        assertEquals("本月还款", transaction.note)
        assertFalse(transaction.autoGenerated)
    }

    @Test
    fun investmentBuyCreatesTransactionWithInvestmentAssetAndDate() {
        val transaction = TransactionFactory.investmentBuy(
            id = "investment-buy",
            amount = Money.cents(30_000),
            accountId = "bank",
            investmentAssetId = "fund",
            categoryId = "investment-input",
            date = LocalDate.of(2026, 6, 28),
            note = "补录基金定投",
        )

        assertEquals(TransactionType.INVESTMENT_BUY, transaction.type)
        assertEquals(Money.cents(30_000), transaction.amount)
        assertEquals("bank", transaction.accountId)
        assertEquals("fund", transaction.investmentAssetId)
        assertEquals("investment-input", transaction.categoryId)
        assertEquals(LocalDate.of(2026, 6, 28), transaction.date)
        assertEquals("补录基金定投", transaction.note)
        assertFalse(transaction.autoGenerated)
    }
}
