package com.yukisora.yukiaccount.data.backup

import com.yukisora.yukiaccount.data.model.AccountEntity
import com.yukisora.yukiaccount.data.model.CategoryEntity
import com.yukisora.yukiaccount.data.model.InvestmentAssetEntity
import com.yukisora.yukiaccount.data.model.RecurringRuleEntity
import com.yukisora.yukiaccount.data.model.SkippedOccurrenceEntity
import com.yukisora.yukiaccount.data.model.TransactionEntity
import com.yukisora.yukiaccount.data.model.ValuationSnapshotEntity
import com.yukisora.yukiaccount.domain.model.AccountType
import com.yukisora.yukiaccount.domain.model.InvestmentType
import com.yukisora.yukiaccount.domain.model.RecurringFrequency
import com.yukisora.yukiaccount.domain.model.TransactionType
import java.time.LocalDate
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class BackupMapperTest {
    @Test
    fun entitiesConvertToBackupDocumentWithSchemaVersion() {
        val document = BackupMapper.toDocument(
            accounts = listOf(account()),
            categories = listOf(category()),
            transactions = listOf(transaction()),
            recurringRules = listOf(recurringRule()),
            investmentAssets = listOf(investment()),
            valuationSnapshots = listOf(valuation()),
            skippedOccurrences = listOf(skippedOccurrence()),
        )

        assertEquals(CURRENT_BACKUP_SCHEMA_VERSION, document.schemaVersion)
        assertEquals("bank", document.accounts.single().id)
        assertEquals("BANK_CARD", document.accounts.single().type)
        assertEquals("EXPENSE", document.transactions.single().type)
        assertEquals("2026-07-08", document.transactions.single().date)
        assertEquals("MONTHLY", document.recurringRules.single().frequency)
        assertEquals("FUND", document.investmentAssets.single().type)
        assertEquals("2026-07-08", document.valuationSnapshots.single().date)
        assertEquals("2026-07-08", document.skippedOccurrences.single().occurrenceDate)
    }

    @Test
    fun unsupportedBackupVersionIsRejected() {
        val invalidJson = """{"schemaVersion":999,"accounts":[],"categories":[],"transactions":[],"recurringRules":[],"investmentAssets":[],"valuationSnapshots":[],"skippedOccurrences":[]}"""

        val result = BackupService().parseForImport(invalidJson)

        assertTrue(result is BackupImportResult.Invalid)
        assertEquals("不支持的备份版本：999", result.reason)
    }

    @Test
    fun duplicateEntityIdsAreRejectedBeforeImport() {
        val document = BackupMapper.toDocument(
            accounts = listOf(account(), account().copy(name = "另一张银行卡")),
            categories = emptyList(),
            transactions = emptyList(),
            recurringRules = emptyList(),
            investmentAssets = emptyList(),
            valuationSnapshots = emptyList(),
            skippedOccurrences = emptyList(),
        )
        val duplicateAccountJson = BackupService().export(document)

        val result = BackupService().parseForImport(duplicateAccountJson)

        assertTrue(result is BackupImportResult.Invalid)
        assertEquals("备份文件包含重复账户 ID", result.reason)
    }

    @Test
    fun duplicateRecurringOccurrencesAreRejectedBeforeImport() {
        val automatic = transaction().copy(
            autoGenerated = true,
            recurringRuleId = "rule",
            occurrenceDate = LocalDate.of(2026, 7, 8),
        )
        assertInvalidImport(
            document = backupDocument(
                transactions = listOf(
                    automatic.copy(id = "auto-1"),
                    automatic.copy(id = "auto-2"),
                ),
            ),
            reason = "备份文件包含重复自动周期流水",
        )

        val skipped = skippedOccurrence()
        assertInvalidImport(
            document = backupDocument(
                skippedOccurrences = listOf(
                    skipped.copy(id = "skip-1"),
                    skipped.copy(id = "skip-2"),
                ),
            ),
            reason = "备份文件包含重复跳过周期记录",
        )
    }

    @Test
    fun transactionWithMissingAccountIsRejectedBeforeImport() {
        val document = BackupMapper.toDocument(
            accounts = emptyList(),
            categories = listOf(category()),
            transactions = listOf(transaction()),
            recurringRules = emptyList(),
            investmentAssets = emptyList(),
            valuationSnapshots = emptyList(),
            skippedOccurrences = emptyList(),
        )
        val invalidReferenceJson = BackupService().export(document)

        val result = BackupService().parseForImport(invalidReferenceJson)

        assertTrue(result is BackupImportResult.Invalid)
        assertEquals("备份文件包含不存在的流水账户 ID", result.reason)
    }

    @Test
    fun transactionWithMissingOptionalReferencesIsRejectedBeforeImport() {
        assertInvalidImport(
            document = backupDocument(
                accounts = listOf(account()),
                transactions = listOf(transaction().copy(targetAccountId = "missing-account")),
            ),
            reason = "备份文件包含不存在的流水目标账户 ID",
        )
        assertInvalidImport(
            document = backupDocument(
                categories = emptyList(),
                transactions = listOf(transaction()),
            ),
            reason = "备份文件包含不存在的流水分类 ID",
        )
        assertInvalidImport(
            document = backupDocument(
                investmentAssets = emptyList(),
                transactions = listOf(transaction().copy(investmentAssetId = "missing-investment")),
            ),
            reason = "备份文件包含不存在的流水投资资产 ID",
        )
        assertInvalidImport(
            document = backupDocument(
                recurringRules = emptyList(),
                transactions = listOf(transaction().copy(recurringRuleId = "missing-rule")),
            ),
            reason = "备份文件包含不存在的流水周期规则 ID",
        )
    }

    @Test
    fun recurringRuleWithMissingReferencesIsRejectedBeforeImport() {
        assertInvalidImport(
            document = backupDocument(
                accounts = emptyList(),
                transactions = emptyList(),
            ),
            reason = "备份文件包含不存在的周期规则账户 ID",
        )
        assertInvalidImport(
            document = backupDocument(
                recurringRules = listOf(recurringRule().copy(targetAccountId = "missing-account")),
            ),
            reason = "备份文件包含不存在的周期规则目标账户 ID",
        )
        assertInvalidImport(
            document = backupDocument(
                categories = emptyList(),
                transactions = emptyList(),
            ),
            reason = "备份文件包含不存在的周期规则分类 ID",
        )
        assertInvalidImport(
            document = backupDocument(
                recurringRules = listOf(recurringRule().copy(investmentAssetId = "missing-investment")),
            ),
            reason = "备份文件包含不存在的周期规则投资资产 ID",
        )
    }

    @Test
    fun valuationWithMissingInvestmentAssetIsRejectedBeforeImport() {
        assertInvalidImport(
            document = backupDocument(
                valuationSnapshots = listOf(valuation().copy(investmentAssetId = "missing-investment")),
            ),
            reason = "备份文件包含不存在的市值快照投资资产 ID",
        )
    }

    @Test
    fun skippedOccurrenceWithMissingRecurringRuleIsRejectedBeforeImport() {
        assertInvalidImport(
            document = backupDocument(
                skippedOccurrences = listOf(skippedOccurrence().copy(recurringRuleId = "missing-rule")),
            ),
            reason = "备份文件包含不存在的跳过周期规则 ID",
        )
    }

    @Test
    fun blankRequiredEntityFieldsAreRejectedBeforeImport() {
        val document = backupDocument()

        assertInvalidImport(
            document = document.copy(accounts = document.accounts.map { it.copy(id = " ") }),
            reason = "备份文件包含空账户 ID",
        )
        assertInvalidImport(
            document = document.copy(categories = document.categories.map { it.copy(name = "") }),
            reason = "备份文件包含空分类名称",
        )
        assertInvalidImport(
            document = document.copy(recurringRules = document.recurringRules.map { it.copy(name = " ") }),
            reason = "备份文件包含空周期规则名称",
        )
        assertInvalidImport(
            document = document.copy(investmentAssets = document.investmentAssets.map { it.copy(name = "") }),
            reason = "备份文件包含空投资资产名称",
        )
    }

    @Test
    fun invalidMoneyFieldsAreRejectedBeforeImport() {
        val document = backupDocument(valuationSnapshots = listOf(valuation()))

        assertInvalidImport(
            document = document.copy(transactions = document.transactions.map { it.copy(amountCents = 0) }),
            reason = "备份文件包含非正数流水金额",
        )
        assertInvalidImport(
            document = document.copy(recurringRules = document.recurringRules.map { it.copy(amountCents = -1) }),
            reason = "备份文件包含非正数周期规则金额",
        )
        assertInvalidImport(
            document = document.copy(investmentAssets = document.investmentAssets.map { it.copy(principalCents = -1) }),
            reason = "备份文件包含负数投资本金",
        )
        assertInvalidImport(
            document = document.copy(investmentAssets = document.investmentAssets.map { it.copy(currentValueCents = -1) }),
            reason = "备份文件包含负数投资市值",
        )
        assertInvalidImport(
            document = document.copy(valuationSnapshots = document.valuationSnapshots.map { it.copy(valueCents = -1) }),
            reason = "备份文件包含负数市值快照金额",
        )
    }

    @Test
    fun invalidDateFieldsAreRejectedBeforeImport() {
        val document = backupDocument()

        assertInvalidImport(
            document = document.copy(accounts = document.accounts.map { it.copy(billingDay = 32) }),
            reason = "备份文件包含无效信用卡账单日",
        )
        assertInvalidImport(
            document = document.copy(accounts = document.accounts.map { it.copy(repaymentDay = 0) }),
            reason = "备份文件包含无效信用卡还款日",
        )
        assertInvalidImport(
            document = document.copy(transactions = document.transactions.map { it.copy(date = "2026-02-30") }),
            reason = "备份文件包含无效日期",
        )
        assertInvalidImport(
            document = document.copy(
                recurringRules = document.recurringRules.map {
                    it.copy(startDate = "2026-08-01", endDate = "2026-07-31")
                },
            ),
            reason = "备份文件包含结束日早于开始日的周期规则",
        )
    }

    @Test
    fun autoGeneratedTransactionWithoutSourceMetadataIsRejectedBeforeImport() {
        val document = backupDocument(
            transactions = listOf(
                transaction().copy(
                    autoGenerated = true,
                    recurringRuleId = "rule",
                    occurrenceDate = null,
                )
            ),
        )

        assertInvalidImport(
            document = document,
            reason = "备份文件包含来源信息不完整的自动流水",
        )
    }

    @Test
    fun unsupportedBackupEnumValuesAreRejectedBeforeImport() {
        val document = backupDocument()

        assertInvalidImport(
            document = document.copy(accounts = document.accounts.map { it.copy(type = "BROKERAGE") }),
            reason = "备份文件包含无效账户类型",
        )
        assertInvalidImport(
            document = document.copy(categories = document.categories.map { it.copy(type = "other") }),
            reason = "备份文件包含无效分类类型",
        )
        assertInvalidImport(
            document = document.copy(transactions = document.transactions.map { it.copy(type = "OTHER") }),
            reason = "备份文件包含无效流水类型",
        )
        assertInvalidImport(
            document = document.copy(recurringRules = document.recurringRules.map { it.copy(frequency = "YEARLY") }),
            reason = "备份文件包含无效周期频率",
        )
        assertInvalidImport(
            document = document.copy(investmentAssets = document.investmentAssets.map { it.copy(type = "STOCK") }),
            reason = "备份文件包含无效投资类型",
        )
    }

    @Test
    fun transactionAndRecurringCategoryTypesMustMatch() {
        val incomeCategory = category().copy(id = "salary", name = "工资", type = "income")
        assertInvalidImport(
            document = backupDocument(
                categories = listOf(incomeCategory),
                transactions = listOf(transaction().copy(categoryId = incomeCategory.id)),
                recurringRules = emptyList(),
            ),
            reason = "备份文件包含分类类型不匹配的流水",
        )

        val investmentCategory = category().copy(id = "investment", name = "投资", type = "investment")
        assertInvalidImport(
            document = backupDocument(
                categories = listOf(investmentCategory),
                transactions = emptyList(),
                recurringRules = listOf(recurringRule().copy(categoryId = investmentCategory.id)),
            ),
            reason = "备份文件包含分类类型不匹配的周期规则",
        )
    }

    @Test
    fun transferCategoryTypeIsAccepted() {
        val document = backupDocument(
            categories = listOf(category().copy(type = "transfer")),
            transactions = emptyList(),
            recurringRules = emptyList(),
        )

        val result = BackupService().parseForImport(BackupService().export(document))

        assertTrue(result is BackupImportResult.Valid)
    }

    @Test
    fun transactionMissingRequiredTargetIsRejectedBeforeImport() {
        val document = backupDocument()

        assertInvalidImport(
            document = document.copy(
                transactions = document.transactions.map { it.copy(type = "TRANSFER", targetAccountId = null) },
            ),
            reason = "备份文件包含缺少目标账户的转账流水",
        )
        assertInvalidImport(
            document = document.copy(
                transactions = document.transactions.map {
                    it.copy(type = "CREDIT_CARD_REPAYMENT", targetAccountId = null)
                },
            ),
            reason = "备份文件包含缺少目标账户的信用卡还款流水",
        )
        assertInvalidImport(
            document = document.copy(
                transactions = document.transactions.map { it.copy(type = "INVESTMENT_BUY", investmentAssetId = null) },
            ),
            reason = "备份文件包含缺少投资资产的投资买入流水",
        )
        assertInvalidImport(
            document = document.copy(
                recurringRules = document.recurringRules.map {
                    it.copy(transactionType = "INVESTMENT_BUY", investmentAssetId = null)
                },
            ),
            reason = "备份文件包含缺少投资资产的定投规则",
        )
    }

    @Test
    fun transactionWithInvalidAccountRolesIsRejectedBeforeImport() {
        val bank = account()
        val cash = account().copy(id = "cash", name = "现金", type = AccountType.CASH)
        val creditCard = account().copy(id = "card", name = "信用卡", type = AccountType.CREDIT_CARD)
        val document = backupDocument(accounts = listOf(bank, cash, creditCard))

        assertInvalidImport(
            document = document.copy(
                transactions = document.transactions.map {
                    it.copy(type = "TRANSFER", targetAccountId = "card")
                },
            ),
            reason = "备份文件包含使用信用卡的普通转账流水",
        )
        assertInvalidImport(
            document = document.copy(
                transactions = document.transactions.map {
                    it.copy(type = "CREDIT_CARD_REPAYMENT", targetAccountId = "cash")
                },
            ),
            reason = "备份文件包含目标不是信用卡的还款流水",
        )
        assertInvalidImport(
            document = document.copy(
                transactions = document.transactions.map { it.copy(type = "INCOME", accountId = "card") },
            ),
            reason = "备份文件包含记入信用卡的收入流水",
        )
        assertInvalidImport(
            document = document.copy(
                transactions = document.transactions.map {
                    it.copy(type = "INVESTMENT_BUY", accountId = "card", investmentAssetId = "fund")
                },
            ),
            reason = "备份文件包含使用信用卡的投资买入流水",
        )
    }

    @Test
    fun backupDocumentConvertsBackToEntities() {
        val document = BackupMapper.toDocument(
            accounts = listOf(account()),
            categories = listOf(category()),
            transactions = listOf(transaction()),
            recurringRules = listOf(recurringRule()),
            investmentAssets = listOf(investment()),
            valuationSnapshots = listOf(valuation()),
            skippedOccurrences = listOf(skippedOccurrence()),
        )

        val entities = BackupMapper.toEntities(document)

        assertEquals(AccountType.BANK_CARD, entities.accounts.single().type)
        assertEquals(LocalDate.of(2026, 7, 8), entities.transactions.single().date)
        assertEquals(RecurringFrequency.MONTHLY, entities.recurringRules.single().frequency)
        assertEquals(InvestmentType.FUND, entities.investmentAssets.single().type)
        assertEquals(LocalDate.of(2026, 7, 8), entities.valuationSnapshots.single().date)
        assertEquals(LocalDate.of(2026, 7, 8), entities.skippedOccurrences.single().occurrenceDate)
    }

    private fun assertInvalidImport(document: BackupDocument, reason: String) {
        val result = BackupService().parseForImport(BackupService().export(document))

        assertTrue(result is BackupImportResult.Invalid)
        assertEquals(reason, result.reason)
    }

    private fun backupDocument(
        accounts: List<AccountEntity> = listOf(account()),
        categories: List<CategoryEntity> = listOf(category()),
        transactions: List<TransactionEntity> = listOf(transaction()),
        recurringRules: List<RecurringRuleEntity> = listOf(recurringRule()),
        investmentAssets: List<InvestmentAssetEntity> = listOf(investment()),
        valuationSnapshots: List<ValuationSnapshotEntity> = emptyList(),
        skippedOccurrences: List<SkippedOccurrenceEntity> = emptyList(),
    ): BackupDocument =
        BackupMapper.toDocument(
            accounts = accounts,
            categories = categories,
            transactions = transactions,
            recurringRules = recurringRules,
            investmentAssets = investmentAssets,
            valuationSnapshots = valuationSnapshots,
            skippedOccurrences = skippedOccurrences,
        )

    private fun account() = AccountEntity(
        id = "bank",
        name = "银行卡",
        type = AccountType.BANK_CARD,
        balanceCents = 1000,
        creditLimitCents = null,
        billingDay = null,
        repaymentDay = null,
        isArchived = false,
        createdAt = 1,
        updatedAt = 2,
    )

    private fun category() = CategoryEntity(
        id = "food",
        name = "餐饮",
        type = "expense",
        isFixedExpense = false,
        sortOrder = 1,
        isArchived = false,
    )

    private fun transaction() = TransactionEntity(
        id = "tx",
        type = TransactionType.EXPENSE,
        amountCents = 500,
        accountId = "bank",
        targetAccountId = null,
        categoryId = "food",
        investmentAssetId = null,
        date = LocalDate.of(2026, 7, 8),
        note = "lunch",
        autoGenerated = false,
        recurringRuleId = null,
        occurrenceDate = null,
        createdAt = 3,
        updatedAt = 4,
    )

    private fun recurringRule() = RecurringRuleEntity(
        id = "rule",
        name = "会员",
        transactionType = TransactionType.EXPENSE,
        amountCents = 1500,
        accountId = "bank",
        targetAccountId = null,
        categoryId = "food",
        investmentAssetId = null,
        frequency = RecurringFrequency.MONTHLY,
        startDate = LocalDate.of(2026, 1, 1),
        endDate = null,
        nextOccurrenceDate = LocalDate.of(2026, 8, 1),
        enabled = true,
        createdAt = 5,
        updatedAt = 6,
    )

    private fun investment() = InvestmentAssetEntity(
        id = "fund",
        name = "基金",
        type = InvestmentType.FUND,
        principalCents = 10000,
        currentValueCents = 10200,
        lastValuationDate = LocalDate.of(2026, 7, 8),
        isArchived = false,
        createdAt = 7,
        updatedAt = 8,
    )

    private fun valuation() = ValuationSnapshotEntity(
        id = "valuation",
        investmentAssetId = "fund",
        date = LocalDate.of(2026, 7, 8),
        valueCents = 10200,
        note = "",
        createdAt = 9,
    )

    private fun skippedOccurrence() = SkippedOccurrenceEntity(
        id = "skip",
        recurringRuleId = "rule",
        occurrenceDate = LocalDate.of(2026, 7, 8),
        reason = "手动跳过",
        createdAt = 10,
    )
}
