package com.yukisora.yukiaccount.data.db

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Update
import com.yukisora.yukiaccount.data.model.AccountEntity
import com.yukisora.yukiaccount.data.model.CategoryEntity
import com.yukisora.yukiaccount.data.model.InvestmentAssetEntity
import com.yukisora.yukiaccount.data.model.RecurringRuleEntity
import com.yukisora.yukiaccount.data.model.SkippedOccurrenceEntity
import com.yukisora.yukiaccount.data.model.TransactionEntity
import com.yukisora.yukiaccount.data.model.ValuationSnapshotEntity
import java.time.LocalDate
import kotlinx.coroutines.flow.Flow

@Dao
interface AccountDao {
    @Query("SELECT * FROM accounts ORDER BY createdAt ASC")
    fun observeAllAccounts(): Flow<List<AccountEntity>>

    @Query("SELECT * FROM accounts WHERE isArchived = 0 ORDER BY createdAt ASC")
    fun observeActiveAccounts(): Flow<List<AccountEntity>>

    @Query("SELECT * FROM accounts WHERE isArchived = 0 ORDER BY createdAt ASC")
    suspend fun activeAccounts(): List<AccountEntity>

    @Query("SELECT * FROM accounts ORDER BY createdAt ASC")
    suspend fun allAccounts(): List<AccountEntity>

    @Query("SELECT * FROM accounts WHERE id = :id")
    suspend fun getById(id: String): AccountEntity?

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsert(account: AccountEntity)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsertAll(accounts: List<AccountEntity>)

    @Update
    suspend fun update(account: AccountEntity)

    @Query("DELETE FROM accounts")
    suspend fun clearAll()
}

@Dao
interface TransactionDao {
    @Query("SELECT * FROM transactions ORDER BY date DESC, createdAt DESC")
    fun observeTransactions(): Flow<List<TransactionEntity>>

    @Query("SELECT * FROM transactions ORDER BY date DESC, createdAt DESC")
    suspend fun allTransactions(): List<TransactionEntity>

    @Query("SELECT * FROM transactions WHERE recurringRuleId = :ruleId AND occurrenceDate = :occurrenceDate LIMIT 1")
    suspend fun findAutoGenerated(ruleId: String, occurrenceDate: LocalDate): TransactionEntity?

    @Query("SELECT * FROM transactions WHERE id IN (:ids)")
    suspend fun transactionsByIds(ids: List<String>): List<TransactionEntity>

    @Insert(onConflict = OnConflictStrategy.ABORT)
    suspend fun insert(transaction: TransactionEntity)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsertAll(transactions: List<TransactionEntity>)

    @Delete
    suspend fun delete(transaction: TransactionEntity)

    @Query("DELETE FROM transactions WHERE id IN (:ids)")
    suspend fun deleteByIds(ids: List<String>): Int

    @Query("DELETE FROM transactions")
    suspend fun clearAll()
}

@Dao
interface RecurringRuleDao {
    @Query("SELECT * FROM recurring_rules WHERE enabled = 1 ORDER BY nextOccurrenceDate ASC")
    suspend fun enabledRules(): List<RecurringRuleEntity>

    @Query("SELECT * FROM recurring_rules ORDER BY nextOccurrenceDate ASC")
    fun observeRules(): Flow<List<RecurringRuleEntity>>

    @Query("SELECT * FROM recurring_rules ORDER BY createdAt ASC")
    suspend fun allRules(): List<RecurringRuleEntity>

    @Query("SELECT * FROM recurring_rules WHERE id = :id LIMIT 1")
    suspend fun getRule(id: String): RecurringRuleEntity?

    @Query("SELECT * FROM skipped_occurrences")
    suspend fun skippedOccurrences(): List<SkippedOccurrenceEntity>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsert(rule: RecurringRuleEntity)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsertAll(rules: List<RecurringRuleEntity>)

    @Update
    suspend fun update(rule: RecurringRuleEntity)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertSkipped(skippedOccurrence: SkippedOccurrenceEntity)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsertSkippedAll(skippedOccurrences: List<SkippedOccurrenceEntity>)

    @Query("DELETE FROM recurring_rules")
    suspend fun clearRules()

    @Query("DELETE FROM skipped_occurrences")
    suspend fun clearSkippedOccurrences()
}

@Dao
interface InvestmentDao {
    @Query("SELECT * FROM investment_assets ORDER BY createdAt ASC")
    fun observeAllInvestments(): Flow<List<InvestmentAssetEntity>>

    @Query("SELECT * FROM investment_assets WHERE isArchived = 0 ORDER BY createdAt ASC")
    fun observeActiveInvestments(): Flow<List<InvestmentAssetEntity>>

    @Query("SELECT * FROM investment_assets WHERE isArchived = 0 ORDER BY createdAt ASC")
    suspend fun activeInvestments(): List<InvestmentAssetEntity>

    @Query("SELECT * FROM investment_assets ORDER BY createdAt ASC")
    suspend fun allInvestments(): List<InvestmentAssetEntity>

    @Query("SELECT * FROM investment_assets WHERE id = :id")
    suspend fun getAsset(id: String): InvestmentAssetEntity?

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsertAsset(asset: InvestmentAssetEntity)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsertAssets(assets: List<InvestmentAssetEntity>)

    @Update
    suspend fun updateAsset(asset: InvestmentAssetEntity)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertValuation(snapshot: ValuationSnapshotEntity)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsertValuations(snapshots: List<ValuationSnapshotEntity>)

    @Query("SELECT * FROM valuation_snapshots ORDER BY date ASC, createdAt ASC")
    suspend fun allValuations(): List<ValuationSnapshotEntity>

    @Query("DELETE FROM investment_assets")
    suspend fun clearAssets()

    @Query("DELETE FROM valuation_snapshots")
    suspend fun clearValuations()
}

@Dao
interface CategoryDao {
    @Query("SELECT * FROM categories WHERE isArchived = 0 ORDER BY sortOrder ASC")
    fun observeActiveCategories(): Flow<List<CategoryEntity>>

    @Query("SELECT * FROM categories WHERE isArchived = 0 ORDER BY sortOrder ASC")
    suspend fun activeCategories(): List<CategoryEntity>

    @Query("SELECT * FROM categories ORDER BY sortOrder ASC")
    suspend fun allCategories(): List<CategoryEntity>

    @Query("SELECT * FROM categories WHERE id = :id LIMIT 1")
    suspend fun getById(id: String): CategoryEntity?

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsert(category: CategoryEntity)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsertAll(categories: List<CategoryEntity>)

    @Query("DELETE FROM categories")
    suspend fun clearAll()
}
