package com.yukisora.yukiaccount.domain.model

import java.time.LocalDate

@JvmInline
value class Money(val cents: Long) : Comparable<Money> {
    operator fun plus(other: Money): Money = Money(cents + other.cents)

    operator fun minus(other: Money): Money = Money(cents - other.cents)

    override fun compareTo(other: Money): Int = cents.compareTo(other.cents)

    companion object {
        val ZERO = Money(0)

        fun cents(value: Long): Money = Money(value)
    }
}

enum class AccountType {
    CASH,
    BANK_CARD,
    ALIPAY,
    WECHAT,
    CREDIT_CARD,
}

data class Account(
    val id: String,
    val name: String,
    val type: AccountType,
    val balance: Money,
    val creditLimit: Money? = null,
    val billingDay: Int? = null,
    val repaymentDay: Int? = null,
    val isArchived: Boolean = false,
)

enum class TransactionType {
    EXPENSE,
    INCOME,
    REFUND,
    TRANSFER,
    CREDIT_CARD_REPAYMENT,
    INVESTMENT_BUY,
}

data class Category(
    val id: String,
    val name: String,
    val type: String,
    val isFixedExpense: Boolean,
    val sortOrder: Int,
    val isArchived: Boolean = false,
)

data class Transaction(
    val id: String,
    val type: TransactionType,
    val amount: Money,
    val accountId: String,
    val targetAccountId: String? = null,
    val categoryId: String? = null,
    val investmentAssetId: String? = null,
    val date: LocalDate,
    val note: String = "",
    val autoGenerated: Boolean = false,
    val recurringRuleId: String? = null,
    val occurrenceDate: LocalDate? = null,
)

enum class InvestmentType {
    FUND,
    GOLD,
    WEALTH_MANAGEMENT,
}

data class InvestmentAsset(
    val id: String,
    val name: String,
    val type: InvestmentType,
    val principal: Money,
    val currentValue: Money,
    val lastValuationDate: LocalDate? = null,
    val isArchived: Boolean = false,
)

data class ValuationSnapshot(
    val id: String,
    val investmentAssetId: String,
    val date: LocalDate,
    val value: Money,
    val note: String = "",
)

data class LedgerState(
    val accounts: List<Account>,
    val investments: List<InvestmentAsset>,
)

enum class RecurringFrequency {
    DAILY,
    WEEKLY,
    MONTHLY,
}

data class RecurringRule(
    val id: String,
    val name: String,
    val transactionType: TransactionType,
    val amount: Money,
    val accountId: String,
    val targetAccountId: String? = null,
    val categoryId: String? = null,
    val investmentAssetId: String? = null,
    val frequency: RecurringFrequency,
    val startDate: LocalDate,
    val endDate: LocalDate? = null,
    val nextOccurrenceDate: LocalDate,
    val enabled: Boolean = true,
)

data class SkippedOccurrence(
    val recurringRuleId: String,
    val occurrenceDate: LocalDate,
    val reason: String = "",
)
