package com.yukisora.yukiaccount.data.backup

import com.yukisora.yukiaccount.data.model.AccountEntity
import com.yukisora.yukiaccount.data.model.CategoryEntity
import com.yukisora.yukiaccount.data.model.InvestmentAssetEntity
import com.yukisora.yukiaccount.data.model.RecurringRuleEntity
import com.yukisora.yukiaccount.data.model.SkippedOccurrenceEntity
import com.yukisora.yukiaccount.data.model.TransactionEntity
import com.yukisora.yukiaccount.data.model.ValuationSnapshotEntity
import com.yukisora.yukiaccount.domain.model.AccountType
import com.yukisora.yukiaccount.domain.model.InvestmentType
import com.yukisora.yukiaccount.domain.model.RecurringFrequency
import com.yukisora.yukiaccount.domain.model.TransactionType
import java.time.LocalDate

data class BackupEntities(
    val accounts: List<AccountEntity>,
    val categories: List<CategoryEntity>,
    val transactions: List<TransactionEntity>,
    val recurringRules: List<RecurringRuleEntity>,
    val investmentAssets: List<InvestmentAssetEntity>,
    val valuationSnapshots: List<ValuationSnapshotEntity>,
    val skippedOccurrences: List<SkippedOccurrenceEntity>,
)

object BackupMapper {
    fun toDocument(
        accounts: List<AccountEntity>,
        categories: List<CategoryEntity>,
        transactions: List<TransactionEntity>,
        recurringRules: List<RecurringRuleEntity>,
        investmentAssets: List<InvestmentAssetEntity>,
        valuationSnapshots: List<ValuationSnapshotEntity>,
        skippedOccurrences: List<SkippedOccurrenceEntity>,
    ): BackupDocument =
        BackupDocument(
            accounts = accounts.map { it.toBackup() },
            categories = categories.map { it.toBackup() },
            transactions = transactions.map { it.toBackup() },
            recurringRules = recurringRules.map { it.toBackup() },
            investmentAssets = investmentAssets.map { it.toBackup() },
            valuationSnapshots = valuationSnapshots.map { it.toBackup() },
            skippedOccurrences = skippedOccurrences.map { it.toBackup() },
        )

    fun toEntities(document: BackupDocument): BackupEntities =
        BackupEntities(
            accounts = document.accounts.map { it.toEntity() },
            categories = document.categories.map { it.toEntity() },
            transactions = document.transactions.map { it.toEntity() },
            recurringRules = document.recurringRules.map { it.toEntity() },
            investmentAssets = document.investmentAssets.map { it.toEntity() },
            valuationSnapshots = document.valuationSnapshots.map { it.toEntity() },
            skippedOccurrences = document.skippedOccurrences.map { it.toEntity() },
        )

    private fun AccountEntity.toBackup(): BackupAccount =
        BackupAccount(
            id = id,
            name = name,
            type = type.name,
            balanceCents = balanceCents,
            creditLimitCents = creditLimitCents,
            billingDay = billingDay,
            repaymentDay = repaymentDay,
            isArchived = isArchived,
            createdAt = createdAt,
            updatedAt = updatedAt,
        )

    private fun CategoryEntity.toBackup(): BackupCategory =
        BackupCategory(
            id = id,
            name = name,
            type = type,
            isFixedExpense = isFixedExpense,
            sortOrder = sortOrder,
            isArchived = isArchived,
        )

    private fun TransactionEntity.toBackup(): BackupTransaction =
        BackupTransaction(
            id = id,
            type = type.name,
            amountCents = amountCents,
            accountId = accountId,
            targetAccountId = targetAccountId,
            categoryId = categoryId,
            investmentAssetId = investmentAssetId,
            date = date.toString(),
            note = note,
            autoGenerated = autoGenerated,
            recurringRuleId = recurringRuleId,
            occurrenceDate = occurrenceDate?.toString(),
            createdAt = createdAt,
            updatedAt = updatedAt,
        )

    private fun RecurringRuleEntity.toBackup(): BackupRecurringRule =
        BackupRecurringRule(
            id = id,
            name = name,
            transactionType = transactionType.name,
            amountCents = amountCents,
            accountId = accountId,
            targetAccountId = targetAccountId,
            categoryId = categoryId,
            investmentAssetId = investmentAssetId,
            frequency = frequency.name,
            startDate = startDate.toString(),
            endDate = endDate?.toString(),
            nextOccurrenceDate = nextOccurrenceDate.toString(),
            enabled = enabled,
            createdAt = createdAt,
            updatedAt = updatedAt,
        )

    private fun InvestmentAssetEntity.toBackup(): BackupInvestmentAsset =
        BackupInvestmentAsset(
            id = id,
            name = name,
            type = type.name,
            principalCents = principalCents,
            currentValueCents = currentValueCents,
            lastValuationDate = lastValuationDate?.toString(),
            isArchived = isArchived,
            createdAt = createdAt,
            updatedAt = updatedAt,
        )

    private fun ValuationSnapshotEntity.toBackup(): BackupValuationSnapshot =
        BackupValuationSnapshot(
            id = id,
            investmentAssetId = investmentAssetId,
            date = date.toString(),
            valueCents = valueCents,
            note = note,
            createdAt = createdAt,
        )

    private fun SkippedOccurrenceEntity.toBackup(): BackupSkippedOccurrence =
        BackupSkippedOccurrence(
            id = id,
            recurringRuleId = recurringRuleId,
            occurrenceDate = occurrenceDate.toString(),
            reason = reason,
            createdAt = createdAt,
        )

    private fun BackupAccount.toEntity(): AccountEntity =
        AccountEntity(
            id = id,
            name = name,
            type = AccountType.valueOf(type),
            balanceCents = balanceCents,
            creditLimitCents = creditLimitCents,
            billingDay = billingDay,
            repaymentDay = repaymentDay,
            isArchived = isArchived,
            createdAt = createdAt,
            updatedAt = updatedAt,
        )

    private fun BackupCategory.toEntity(): CategoryEntity =
        CategoryEntity(
            id = id,
            name = name,
            type = type,
            isFixedExpense = isFixedExpense,
            sortOrder = sortOrder,
            isArchived = isArchived,
        )

    private fun BackupTransaction.toEntity(): TransactionEntity =
        TransactionEntity(
            id = id,
            type = TransactionType.valueOf(type),
            amountCents = amountCents,
            accountId = accountId,
            targetAccountId = targetAccountId,
            categoryId = categoryId,
            investmentAssetId = investmentAssetId,
            date = LocalDate.parse(date),
            note = note,
            autoGenerated = autoGenerated,
            recurringRuleId = recurringRuleId,
            occurrenceDate = occurrenceDate?.let(LocalDate::parse),
            createdAt = createdAt,
            updatedAt = updatedAt,
        )

    private fun BackupRecurringRule.toEntity(): RecurringRuleEntity =
        RecurringRuleEntity(
            id = id,
            name = name,
            transactionType = TransactionType.valueOf(transactionType),
            amountCents = amountCents,
            accountId = accountId,
            targetAccountId = targetAccountId,
            categoryId = categoryId,
            investmentAssetId = investmentAssetId,
            frequency = RecurringFrequency.valueOf(frequency),
            startDate = LocalDate.parse(startDate),
            endDate = endDate?.let(LocalDate::parse),
            nextOccurrenceDate = LocalDate.parse(nextOccurrenceDate),
            enabled = enabled,
            createdAt = createdAt,
            updatedAt = updatedAt,
        )

    private fun BackupInvestmentAsset.toEntity(): InvestmentAssetEntity =
        InvestmentAssetEntity(
            id = id,
            name = name,
            type = InvestmentType.valueOf(type),
            principalCents = principalCents,
            currentValueCents = currentValueCents,
            lastValuationDate = lastValuationDate?.let(LocalDate::parse),
            isArchived = isArchived,
            createdAt = createdAt,
            updatedAt = updatedAt,
        )

    private fun BackupValuationSnapshot.toEntity(): ValuationSnapshotEntity =
        ValuationSnapshotEntity(
            id = id,
            investmentAssetId = investmentAssetId,
            date = LocalDate.parse(date),
            valueCents = valueCents,
            note = note,
            createdAt = createdAt,
        )

    private fun BackupSkippedOccurrence.toEntity(): SkippedOccurrenceEntity =
        SkippedOccurrenceEntity(
            id = id,
            recurringRuleId = recurringRuleId,
            occurrenceDate = LocalDate.parse(occurrenceDate),
            reason = reason,
            createdAt = createdAt,
        )
}
