package com.yukisora.yukiaccount.data.backup

import kotlinx.serialization.Serializable

const val CURRENT_BACKUP_SCHEMA_VERSION = 1

@Serializable
data class BackupDocument(
    val schemaVersion: Int = CURRENT_BACKUP_SCHEMA_VERSION,
    val accounts: List<BackupAccount>,
    val categories: List<BackupCategory>,
    val transactions: List<BackupTransaction>,
    val recurringRules: List<BackupRecurringRule>,
    val investmentAssets: List<BackupInvestmentAsset>,
    val valuationSnapshots: List<BackupValuationSnapshot>,
    val skippedOccurrences: List<BackupSkippedOccurrence>,
)

@Serializable
data class BackupAccount(
    val id: String,
    val name: String,
    val type: String,
    val balanceCents: Long,
    val creditLimitCents: Long?,
    val billingDay: Int?,
    val repaymentDay: Int?,
    val isArchived: Boolean,
    val createdAt: Long,
    val updatedAt: Long,
)

@Serializable
data class BackupCategory(
    val id: String,
    val name: String,
    val type: String,
    val isFixedExpense: Boolean,
    val sortOrder: Int,
    val isArchived: Boolean,
)

@Serializable
data class BackupTransaction(
    val id: String,
    val type: String,
    val amountCents: Long,
    val accountId: String,
    val targetAccountId: String?,
    val categoryId: String?,
    val investmentAssetId: String?,
    val date: String,
    val note: String,
    val autoGenerated: Boolean,
    val recurringRuleId: String?,
    val occurrenceDate: String?,
    val createdAt: Long,
    val updatedAt: Long,
)

@Serializable
data class BackupRecurringRule(
    val id: String,
    val name: String,
    val transactionType: String,
    val amountCents: Long,
    val accountId: String,
    val targetAccountId: String?,
    val categoryId: String?,
    val investmentAssetId: String?,
    val frequency: String,
    val startDate: String,
    val endDate: String?,
    val nextOccurrenceDate: String,
    val enabled: Boolean,
    val createdAt: Long,
    val updatedAt: Long,
)

@Serializable
data class BackupInvestmentAsset(
    val id: String,
    val name: String,
    val type: String,
    val principalCents: Long,
    val currentValueCents: Long,
    val lastValuationDate: String?,
    val isArchived: Boolean,
    val createdAt: Long,
    val updatedAt: Long,
)

@Serializable
data class BackupValuationSnapshot(
    val id: String,
    val investmentAssetId: String,
    val date: String,
    val valueCents: Long,
    val note: String,
    val createdAt: Long,
)

@Serializable
data class BackupSkippedOccurrence(
    val id: String,
    val recurringRuleId: String,
    val occurrenceDate: String,
    val reason: String,
    val createdAt: Long,
)
