package com.yukisora.yukiaccount.data.backup

import java.time.LocalDate
import java.time.format.DateTimeParseException
import kotlinx.serialization.SerializationException
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json

class BackupService(
    private val json: Json = Json {
        prettyPrint = true
        ignoreUnknownKeys = false
        encodeDefaults = true
    },
) {
    fun export(document: BackupDocument): String =
        json.encodeToString(document.copy(schemaVersion = CURRENT_BACKUP_SCHEMA_VERSION))

    fun parseForImport(rawJson: String): BackupImportResult {
        val document = try {
            json.decodeFromString<BackupDocument>(rawJson)
        } catch (error: SerializationException) {
            return BackupImportResult.Invalid("备份文件格式无效")
        } catch (error: IllegalArgumentException) {
            return BackupImportResult.Invalid("备份文件内容无效")
        }

        if (document.schemaVersion != CURRENT_BACKUP_SCHEMA_VERSION) {
            return BackupImportResult.Invalid("不支持的备份版本：${document.schemaVersion}")
        }

        document.basicFieldReason()?.let { reason ->
            return BackupImportResult.Invalid(reason)
        }

        document.duplicateIdReason()?.let { reason ->
            return BackupImportResult.Invalid(reason)
        }

        document.referenceIntegrityReason()?.let { reason ->
            return BackupImportResult.Invalid(reason)
        }

        return BackupImportResult.Valid(document)
    }

    private fun BackupDocument.basicFieldReason(): String? {
        listOf(
            "账户" to accounts.map { it.id },
            "分类" to categories.map { it.id },
            "流水" to transactions.map { it.id },
            "周期规则" to recurringRules.map { it.id },
            "投资资产" to investmentAssets.map { it.id },
            "市值快照" to valuationSnapshots.map { it.id },
            "跳过周期记录" to skippedOccurrences.map { it.id },
        ).firstOrNull { (_, ids) -> ids.any(String::isBlank) }
            ?.let { (label, _) -> return "备份文件包含空${label} ID" }

        listOf(
            "账户" to accounts.map { it.name },
            "分类" to categories.map { it.name },
            "周期规则" to recurringRules.map { it.name },
            "投资资产" to investmentAssets.map { it.name },
        ).firstOrNull { (_, names) -> names.any(String::isBlank) }
            ?.let { (label, _) -> return "备份文件包含空${label}名称" }

        if (transactions.any { it.amountCents <= 0 }) {
            return "备份文件包含非正数流水金额"
        }
        if (recurringRules.any { it.amountCents <= 0 }) {
            return "备份文件包含非正数周期规则金额"
        }
        if (investmentAssets.any { it.principalCents < 0 }) {
            return "备份文件包含负数投资本金"
        }
        if (investmentAssets.any { it.currentValueCents < 0 }) {
            return "备份文件包含负数投资市值"
        }
        if (valuationSnapshots.any { it.valueCents < 0 }) {
            return "备份文件包含负数市值快照金额"
        }
        if (accounts.any { it.creditLimitCents != null && it.creditLimitCents < 0 }) {
            return "备份文件包含负数信用额度"
        }
        if (accounts.any { it.billingDay != null && it.billingDay !in 1..31 }) {
            return "备份文件包含无效信用卡账单日"
        }
        if (accounts.any { it.repaymentDay != null && it.repaymentDay !in 1..31 }) {
            return "备份文件包含无效信用卡还款日"
        }

        if (allDateValues().any { it.toLocalDateOrNull() == null }) {
            return "备份文件包含无效日期"
        }
        if (recurringRules.any { rule ->
                val startDate = LocalDate.parse(rule.startDate)
                rule.endDate?.let(LocalDate::parse)?.isBefore(startDate) == true
            }
        ) {
            return "备份文件包含结束日早于开始日的周期规则"
        }
        if (recurringRules.any { rule ->
                LocalDate.parse(rule.nextOccurrenceDate).isBefore(LocalDate.parse(rule.startDate))
            }
        ) {
            return "备份文件包含下次执行日早于开始日的周期规则"
        }
        if (transactions.any { transaction ->
                transaction.autoGenerated &&
                    (transaction.recurringRuleId.isNullOrBlank() || transaction.occurrenceDate.isNullOrBlank())
            }
        ) {
            return "备份文件包含来源信息不完整的自动流水"
        }

        return null
    }

    private fun BackupDocument.allDateValues(): List<String> =
        buildList {
            transactions.forEach { transaction ->
                add(transaction.date)
                transaction.occurrenceDate?.let(::add)
            }
            recurringRules.forEach { rule ->
                add(rule.startDate)
                rule.endDate?.let(::add)
                add(rule.nextOccurrenceDate)
            }
            investmentAssets.forEach { it.lastValuationDate?.let(::add) }
            valuationSnapshots.forEach { add(it.date) }
            skippedOccurrences.forEach { add(it.occurrenceDate) }
        }

    private fun String.toLocalDateOrNull(): LocalDate? =
        try {
            LocalDate.parse(this)
        } catch (error: DateTimeParseException) {
            null
        }

    private fun BackupDocument.duplicateIdReason(): String? =
        listOf(
            "账户" to accounts.map { it.id },
            "分类" to categories.map { it.id },
            "流水" to transactions.map { it.id },
            "周期规则" to recurringRules.map { it.id },
            "投资资产" to investmentAssets.map { it.id },
            "市值快照" to valuationSnapshots.map { it.id },
            "跳过周期记录" to skippedOccurrences.map { it.id },
        ).firstOrNull { (_, ids) -> ids.hasDuplicate() }
            ?.let { (label, _) -> "备份文件包含重复${label} ID" }

    private fun List<String>.hasDuplicate(): Boolean =
        size != toSet().size

    private fun BackupDocument.referenceIntegrityReason(): String? {
        val accountIds = accounts.map { it.id }.toSet()
        val categoryIds = categories.map { it.id }.toSet()
        val investmentAssetIds = investmentAssets.map { it.id }.toSet()
        val recurringRuleIds = recurringRules.map { it.id }.toSet()

        if (transactions.any { it.accountId !in accountIds }) {
            return "备份文件包含不存在的流水账户 ID"
        }
        if (transactions.any { it.targetAccountId != null && it.targetAccountId !in accountIds }) {
            return "备份文件包含不存在的流水目标账户 ID"
        }
        if (transactions.any { it.categoryId != null && it.categoryId !in categoryIds }) {
            return "备份文件包含不存在的流水分类 ID"
        }
        if (transactions.any { it.investmentAssetId != null && it.investmentAssetId !in investmentAssetIds }) {
            return "备份文件包含不存在的流水投资资产 ID"
        }
        if (transactions.any { it.recurringRuleId != null && it.recurringRuleId !in recurringRuleIds }) {
            return "备份文件包含不存在的流水周期规则 ID"
        }
        if (recurringRules.any { it.accountId !in accountIds }) {
            return "备份文件包含不存在的周期规则账户 ID"
        }
        if (recurringRules.any { it.targetAccountId != null && it.targetAccountId !in accountIds }) {
            return "备份文件包含不存在的周期规则目标账户 ID"
        }
        if (recurringRules.any { it.categoryId != null && it.categoryId !in categoryIds }) {
            return "备份文件包含不存在的周期规则分类 ID"
        }
        if (recurringRules.any {
                it.investmentAssetId != null && it.investmentAssetId !in investmentAssetIds
            }
        ) {
            return "备份文件包含不存在的周期规则投资资产 ID"
        }
        if (valuationSnapshots.any { it.investmentAssetId !in investmentAssetIds }) {
            return "备份文件包含不存在的市值快照投资资产 ID"
        }
        if (skippedOccurrences.any { it.recurringRuleId !in recurringRuleIds }) {
            return "备份文件包含不存在的跳过周期规则 ID"
        }

        return null
    }
}

sealed interface BackupImportResult {
    data class Valid(val document: BackupDocument) : BackupImportResult
    data class Invalid(val reason: String) : BackupImportResult
}
